/**
 * ReportPage — Step 8 (final deliverable).
 *
 * Displays the InvestigationReport generated by the Discovery Engine.
 * Includes summary narrative, ranked insights, hypothesis confidence chart
 * (via Recharts), and suggested follow-up actions.
 */

interface ReportPageProps {
  sessionId: string
}

export default function ReportPage({ sessionId }: ReportPageProps) {
  // TODO: Fetch report via GET /investigate/{id}/report
  // TODO: Render summary, insights list, confidence bar chart (Recharts)
  // TODO: "Start new investigation" button to reset workflow

  return (
    <div className="py-8">
      <h2 className="text-2xl font-bold text-gray-800 mb-4">
        Investigation Report
      </h2>
      <p className="text-gray-600">
        Session: {sessionId} — Final discoveries and insights.
      </p>
      {/* TODO: Report summary, insight cards, Recharts visualizations */}
    </div>
  )
}
